// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB750dlPMJXyv5sKfY_RPQGK-tKHWtiNlo',
    appId: '1:189981234188:android:5578e8ca96b49696a7ca29',
    messagingSenderId: '189981234188',
    projectId: 'fooddelivery-dea60',
    storageBucket: 'fooddelivery-dea60.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-XUA5YoJEDG6qw5fy1xpdVxkjVhx-zs',
    appId: '1:189981234188:web:982c6b338ba3f71fa7ca29',
    messagingSenderId: '189981234188',
    projectId: 'fooddelivery-dea60',
    authDomain: 'fooddelivery-dea60.firebaseapp.com',
    storageBucket: 'fooddelivery-dea60.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-XUA5YoJEDG6qw5fy1xpdVxkjVhx-zs',
    appId: '1:189981234188:web:982c6b338ba3f71fa7ca29',
    messagingSenderId: '189981234188',
    projectId: 'fooddelivery-dea60',
    authDomain: 'fooddelivery-dea60.firebaseapp.com',
    storageBucket: 'fooddelivery-dea60.appspot.com',
  );

}